version = 0.1

[default.deploy.parameters]
stack_name = "aws-lambda-getvpamtoken"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CybrKey=<SecretsManagerSecretArn> CybrTenantId=<CyberArkTenantId> CybrServiceAccountId=<CyberArkServiceAccountId> CybrRegion=<CyberArkTenantRegion>"