AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that creates a jwt for CyberArk Vendor PAM or CyberArk Secure Web Sessions.
Resources:
  CybrTokenGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: NE-ISPSS-TOKEN-GATEWAY
      StageName: Staging

  CyrbTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: function/.
      Description: Creates a jwt for CyberArk Vendor PAM or CyberArk Secure Web Sessions
      Timeout: 5
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secetsmanager:${AWS::Region}:${AWS::AccountId}:secret:PIN-SEC-HUB-DEV/VPAM-B64-KEY-1P8Whs"
      Tracing: Active
      Events:
        HttpRequest:
          Type: Api
          Properties:
            RestApiId: !Ref CybrTokenGateway
            Path: /token
            Method: GET
            Auth:
              ApiFunctionAuth:
                ApiKeyRequired: false

Outputs:
  CybrTokenGateway:
    Description: 'API Gateway endpoint URL for Staging stage for Cybr Token Function'
    Value: !Sub 'https://${CybrTokenGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/token/'
  CybrTokenGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref CybrTokenGateway
    Export:
      Name: CybrTokenGateway-RestApiId
  CybrTokenGatewayRootResourceId:
    Value: !GetAtt CybrTokenGateway.RootResourceId
    Export:
      Name: CybrTokenGateway-RootResourceId