AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that creates a jwt for CyberArk Vendor PAM or CyberArk Secure Web Sessions.
Parameters:
  CybrRegion:
    Type: String
    Description: The region where the CyberArk Remote Access Serivce is hosted
    Default: us
  CybrTenantId:
    Type: String
    Description: The tenant id of the CyberArk Remote Access Service
    Default: 1
  CybrServiceAccountId:
    Type: String
    Description: The service account id of the CyberArk Remote Access Service
    Default: 1
  CybrKey:
    Type: String
    Description: The ARN of the secret containing the CyberArk Remote Access Service key
    Default: 1

Resources:
  CybrTokenGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: NE-ISPSS-TOKEN-GATEWAY
      StageName: Staging

  CyrbTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: function/.
      Description: Creates a jwt for CyberArk Vendor PAM or CyberArk Secure Web Sessions
      Timeout: 5
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:PIN-SEC-HUB-DEV/VPAM-B64-KEY-1P8Whs"
      Tracing: Active
      Environment:
        Variables:
          CYBR_REGION: !Ref CybrRegion
          CYBR_TENANT_ID: !Ref CybrTenantId
          CYBR_SERVICE_ACCOUNT_ID: !Ref CybrServiceAccountId
          CYBR_KEY: !Ref CybrKey
      Events:
        HttpRequest:
          Type: Api
          Properties:
            RestApiId: !Ref CybrTokenGateway
            Path: /token
            Method: GET
            Auth:
              ApiFunctionAuth:
                ApiKeyRequired: false

Outputs:
  CybrTokenGateway:
    Description: 'API Gateway endpoint URL for Staging stage for Cybr Token Function'
    Value: !Sub 'https://${CybrTokenGateway}.execute-api.${AWS::Region}.amazonaws.com/Staging/token/'
  CybrTokenGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref CybrTokenGateway
    Export:
      Name: CybrTokenGateway-RestApiId
  CybrTokenGatewayRootResourceId:
    Value: !GetAtt CybrTokenGateway.RootResourceId
    Export:
      Name: CybrTokenGateway-RootResourceId